export interface Animal {
  id: string;
  name: string;
  species: "Dog" | "Cat";
  breed: string;
  sex: "Male" | "Female";
  age: string;
  size: "Small" | "Medium" | "Large";
  colorMarkings: string;
  rescueStatus: "Reported" | "Rescued" | "In Shelter";
  adoptionStatus: "Available" | "Pending" | "Adopted" | "Unavailable";
  healthStatus: "Healthy" | "Under Treatment" | "Recovering" | "Critical";
  vaccinationStatus: "Vaccinated" | "Not Fully Vaccinated";
  heartRate: string;
  location: string;
  dateRescued: string;
  dateAdded: string;
  lastUpdated: string;
  bio: string;
  photo: string;
}

export const MOCK_ANIMALS: Animal[] = [
  {
    id: "ANM-2026-001",
    name: "Max",
    species: "Dog",
    breed: "Golden Retriever",
    sex: "Male",
    age: "2 years",
    size: "Large",
    colorMarkings: "Golden coat, white chest patch",
    rescueStatus: "Rescued",
    adoptionStatus: "Available",
    healthStatus: "Healthy",
    vaccinationStatus: "Vaccinated",
    heartRate: "82 BPM",
    location: "Main Shelter — Kennel A3",
    dateRescued: "Jan 14, 2026",
    dateAdded: "Jan 15, 2026",
    lastUpdated: "Jul 8, 2026",
    bio: "Friendly and energetic, loves fetch and long walks. Great with kids and other dogs.",
    photo: "https://images.unsplash.com/photo-1552053831-71594a27632d?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: "ANM-2026-002",
    name: "Luna",
    species: "Cat",
    breed: "Siamese",
    sex: "Female",
    age: "6 months",
    size: "Small",
    colorMarkings: "Cream coat, dark seal points",
    rescueStatus: "In Shelter",
    adoptionStatus: "Pending",
    healthStatus: "Under Treatment",
    vaccinationStatus: "Not Fully Vaccinated",
    heartRate: "142 BPM",
    location: "Medical Wing — Room 2",
    dateRescued: "Mar 2, 2026",
    dateAdded: "Mar 3, 2026",
    lastUpdated: "Jul 9, 2026",
    bio: "Recovering from a minor injury. Curious, vocal, and warming up to new people quickly.",
    photo: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: "ANM-2026-003",
    name: "Rocky",
    species: "Dog",
    breed: "German Shepherd",
    sex: "Male",
    age: "4 years",
    size: "Large",
    colorMarkings: "Black and tan saddle",
    rescueStatus: "In Shelter",
    adoptionStatus: "Unavailable",
    healthStatus: "Recovering",
    vaccinationStatus: "Vaccinated",
    heartRate: "76 BPM",
    location: "Main Shelter — Kennel B1",
    dateRescued: "Feb 20, 2026",
    dateAdded: "Feb 21, 2026",
    lastUpdated: "Jul 5, 2026",
    bio: "Under routine vet monitoring after intake. Alert, loyal, and highly trainable.",
    photo: "https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: "ANM-2026-004",
    name: "Bella",
    species: "Dog",
    breed: "Poodle",
    sex: "Female",
    age: "1 year",
    size: "Medium",
    colorMarkings: "Solid apricot coat",
    rescueStatus: "Rescued",
    adoptionStatus: "Available",
    healthStatus: "Healthy",
    vaccinationStatus: "Vaccinated",
    heartRate: "88 BPM",
    location: "Main Shelter — Kennel A5",
    dateRescued: "Apr 10, 2026",
    dateAdded: "Apr 11, 2026",
    lastUpdated: "Jul 7, 2026",
    bio: "Playful and hypoallergenic-coated. Enjoys grooming sessions and short car rides.",
    photo: "https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: "ANM-2026-005",
    name: "Oliver",
    species: "Cat",
    breed: "Maine Coon",
    sex: "Male",
    age: "3 years",
    size: "Large",
    colorMarkings: "Brown tabby, tufted ears",
    rescueStatus: "Rescued",
    adoptionStatus: "Available",
    healthStatus: "Healthy",
    vaccinationStatus: "Vaccinated",
    heartRate: "128 BPM",
    location: "Cattery — Room 1",
    dateRescued: "Jan 28, 2026",
    dateAdded: "Jan 29, 2026",
    lastUpdated: "Jul 6, 2026",
    bio: "Gentle giant with a calm temperament. Prefers quiet homes and sunny windowsills.",
    photo: "https://images.unsplash.com/photo-1533738363-b7f9aef128ce?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: "ANM-2026-006",
    name: "Daisy",
    species: "Dog",
    breed: "Beagle",
    sex: "Female",
    age: "5 years",
    size: "Medium",
    colorMarkings: "Tricolor: white, black, tan",
    rescueStatus: "Rescued",
    adoptionStatus: "Available",
    healthStatus: "Healthy",
    vaccinationStatus: "Vaccinated",
    heartRate: "90 BPM",
    location: "Main Shelter — Kennel A1",
    dateRescued: "Nov 3, 2025",
    dateAdded: "Nov 4, 2025",
    lastUpdated: "Jul 3, 2026",
    bio: "Sweet-natured and food-motivated. Settles in fast and gets along with everyone.",
    photo: "https://images.unsplash.com/photo-1505628346881-b72b27e84530?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: "ANM-2026-007",
    name: "Milo",
    species: "Cat",
    breed: "Bengal",
    sex: "Male",
    age: "2 years",
    size: "Medium",
    colorMarkings: "Spotted rosette coat, golden base",
    rescueStatus: "Rescued",
    adoptionStatus: "Available",
    healthStatus: "Healthy",
    vaccinationStatus: "Vaccinated",
    heartRate: "134 BPM",
    location: "Cattery — Room 3",
    dateRescued: "Dec 12, 2025",
    dateAdded: "Dec 13, 2025",
    lastUpdated: "Jun 30, 2026",
    bio: "Athletic and inquisitive. Needs an active household with climbing space.",
    photo: "https://images.unsplash.com/photo-1513360309081-36f5e878f210?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: "ANM-2026-008",
    name: "Coco",
    species: "Dog",
    breed: "Labrador",
    sex: "Female",
    age: "3 years",
    size: "Large",
    colorMarkings: "Solid chocolate brown",
    rescueStatus: "Rescued",
    adoptionStatus: "Pending",
    healthStatus: "Healthy",
    vaccinationStatus: "Vaccinated",
    heartRate: "85 BPM",
    location: "Main Shelter — Kennel A2",
    dateRescued: "Feb 1, 2026",
    dateAdded: "Feb 2, 2026",
    lastUpdated: "Jul 9, 2026",
    bio: "Adoption paperwork in review. Sociable, obedient, and great on a leash.",
    photo: "https://images.unsplash.com/photo-1537151625747-7ae87041895a?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: "ANM-2026-009",
    name: "Simba",
    species: "Cat",
    breed: "Persian",
    sex: "Male",
    age: "4 years",
    size: "Medium",
    colorMarkings: "Cream, long-haired",
    rescueStatus: "In Shelter",
    adoptionStatus: "Unavailable",
    healthStatus: "Under Treatment",
    vaccinationStatus: "Not Fully Vaccinated",
    heartRate: "No Data",
    location: "Medical Wing — Room 1",
    dateRescued: "May 6, 2026",
    dateAdded: "May 7, 2026",
    lastUpdated: "Jul 9, 2026",
    bio: "Receiving ongoing dental treatment. Affectionate lap cat once comfortable.",
    photo: "https://images.unsplash.com/photo-1614273147774-411b1ef56306?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: "ANM-2026-010",
    name: "Charlie",
    species: "Dog",
    breed: "Boxer",
    sex: "Male",
    age: "1.5 years",
    size: "Large",
    colorMarkings: "Fawn with white markings",
    rescueStatus: "Rescued",
    adoptionStatus: "Available",
    healthStatus: "Healthy",
    vaccinationStatus: "Vaccinated",
    heartRate: "94 BPM",
    location: "Main Shelter — Kennel B4",
    dateRescued: "Jun 2, 2026",
    dateAdded: "Jun 3, 2026",
    lastUpdated: "Jul 8, 2026",
    bio: "Bouncy and affectionate. Needs a yard or daily runs to stay content.",
    photo: "https://images.unsplash.com/photo-1543466835-00a7907e9de1?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: "ANM-2026-011",
    name: "Nala",
    species: "Cat",
    breed: "Ragdoll",
    sex: "Female",
    age: "1 year",
    size: "Medium",
    colorMarkings: "Seal point, blue eyes",
    rescueStatus: "Rescued",
    adoptionStatus: "Available",
    healthStatus: "Healthy",
    vaccinationStatus: "Vaccinated",
    heartRate: "121 BPM",
    location: "Cattery — Room 2",
    dateRescued: "Apr 22, 2026",
    dateAdded: "Apr 23, 2026",
    lastUpdated: "Jul 4, 2026",
    bio: "Docile and affectionate, goes limp when picked up. Loves being held.",
    photo: "https://images.unsplash.com/photo-1574158622643-69d34d72650a?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: "ANM-2026-012",
    name: "Lucy",
    species: "Dog",
    breed: "Dachshund",
    sex: "Female",
    age: "2 years",
    size: "Small",
    colorMarkings: "Red coat, short-haired",
    rescueStatus: "Rescued",
    adoptionStatus: "Available",
    healthStatus: "Healthy",
    vaccinationStatus: "Vaccinated",
    heartRate: "96 BPM",
    location: "Main Shelter — Kennel A4",
    dateRescued: "Mar 15, 2026",
    dateAdded: "Mar 16, 2026",
    lastUpdated: "Jul 2, 2026",
    bio: "Spirited and stubborn in the best way. Loves burrowing into blankets.",
    photo: "https://images.unsplash.com/photo-1529429617329-8468a9776562?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: "ANM-2026-013",
    name: "Leo",
    species: "Cat",
    breed: "Sphynx",
    sex: "Male",
    age: "3 years",
    size: "Small",
    colorMarkings: "Hairless, pinkish-grey skin",
    rescueStatus: "In Shelter",
    adoptionStatus: "Pending",
    healthStatus: "Recovering",
    vaccinationStatus: "Vaccinated",
    heartRate: "138 BPM",
    location: "Medical Wing — Room 3",
    dateRescued: "Jan 8, 2026",
    dateAdded: "Jan 9, 2026",
    lastUpdated: "Jul 1, 2026",
    bio: "Needs regular skin care due to lack of coat. Warm, social, and vocal.",
    photo: "https://images.unsplash.com/photo-1520315342629-6ea920342047?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: "ANM-2026-014",
    name: "Cooper",
    species: "Dog",
    breed: "Bulldog",
    sex: "Male",
    age: "4 years",
    size: "Medium",
    colorMarkings: "Brindle with white chest",
    rescueStatus: "Rescued",
    adoptionStatus: "Available",
    healthStatus: "Healthy",
    vaccinationStatus: "Vaccinated",
    heartRate: "80 BPM",
    location: "Main Shelter — Kennel B2",
    dateRescued: "Oct 19, 2025",
    dateAdded: "Oct 20, 2025",
    lastUpdated: "Jun 28, 2026",
    bio: "Laid-back companion who's happiest napping in a sunbeam nearby.",
    photo: "https://images.unsplash.com/photo-1517423568366-8b83523034fd?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: "ANM-2026-015",
    name: "Zoe",
    species: "Cat",
    breed: "British Shorthair",
    sex: "Female",
    age: "2 years",
    size: "Medium",
    colorMarkings: "Solid blue-grey coat",
    rescueStatus: "Rescued",
    adoptionStatus: "Available",
    healthStatus: "Healthy",
    vaccinationStatus: "Vaccinated",
    heartRate: "118 BPM",
    location: "Cattery — Room 4",
    dateRescued: "Feb 27, 2026",
    dateAdded: "Feb 28, 2026",
    lastUpdated: "Jul 5, 2026",
    bio: "Independent and easygoing. Content to observe the household from a perch.",
    photo: "https://images.unsplash.com/photo-1573865526739-10659fec78a5?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: "ANM-2026-016",
    name: "Teddy",
    species: "Dog",
    breed: "Shih Tzu",
    sex: "Male",
    age: "8 months",
    size: "Small",
    colorMarkings: "White and gold coat",
    rescueStatus: "Rescued",
    adoptionStatus: "Available",
    healthStatus: "Healthy",
    vaccinationStatus: "Not Fully Vaccinated",
    heartRate: "104 BPM",
    location: "Main Shelter — Kennel A6",
    dateRescued: "May 30, 2026",
    dateAdded: "May 31, 2026",
    lastUpdated: "Jul 9, 2026",
    bio: "Small, cuddly, and low-energy. Ideal for apartment living and first-time owners.",
    photo: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: "ANM-2026-017",
    name: "Mia",
    species: "Cat",
    breed: "Abyssinian",
    sex: "Female",
    age: "3 years",
    size: "Small",
    colorMarkings: "Ruddy ticked coat",
    rescueStatus: "Rescued",
    adoptionStatus: "Available",
    healthStatus: "Healthy",
    vaccinationStatus: "Vaccinated",
    heartRate: "125 BPM",
    location: "Cattery — Room 5",
    dateRescued: "Mar 9, 2026",
    dateAdded: "Mar 10, 2026",
    lastUpdated: "Jul 6, 2026",
    bio: "Active and playful, always first to greet visitors at the door.",
    photo: "https://images.unsplash.com/photo-1536590158209-e9d615d525e4?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: "ANM-2026-018",
    name: "Duke",
    species: "Dog",
    breed: "Rottweiler",
    sex: "Male",
    age: "5 years",
    size: "Large",
    colorMarkings: "Black with rust markings",
    rescueStatus: "In Shelter",
    adoptionStatus: "Unavailable",
    healthStatus: "Critical",
    vaccinationStatus: "Vaccinated",
    heartRate: "No Data",
    location: "Medical Wing — Room 4",
    dateRescued: "Jun 20, 2026",
    dateAdded: "Jun 21, 2026",
    lastUpdated: "Jul 10, 2026",
    bio: "Currently held for a returning foster review. Calm, protective, well-trained.",
    photo: "https://images.unsplash.com/photo-1567752881298-894bb81f9379?q=80&w=800&auto=format&fit=crop"
  }
];

export function getAnimalById(id: string): Animal | undefined {
  return MOCK_ANIMALS.find((animal) => animal.id === id);
}