import type { Animal, Model3dStatus } from '@/types';

const NO_3D = { model3dUrl: null, model3dStatus: 'none' as Model3dStatus };

export const FEATURED_ANIMALS: Animal[] = [
  {
    id: 'A001',
    name: 'Luna',
    species: 'Dog',
    breed: 'Golden Retriever Mix',
    sex: 'Female',
    age: '2 years',
    size: 'Large',
    colorMarkings: 'Golden with white chest',
    rescueStatus: 'In Shelter',
    adoptionStatus: 'Available',
    healthStatus: 'Healthy',
    vaccinationStatus: 'Vaccinated',
    heartRate: 'Normal',
    location: 'Manila City Shelter',
    dateRescued: '2026-05-10',
    dateAdded: '2026-05-12',
    lastUpdated: '2026-07-15',
    bio: 'Sweet, energetic girl who loves belly rubs and long walks.',
    photo: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=600&q=80',
    ...NO_3D,
  },
  {
    id: 'A002',
    name: 'Milo',
    species: 'Cat',
    breed: 'Tabby',
    sex: 'Male',
    age: '1 year',
    size: 'Small',
    colorMarkings: 'Orange tabby with white paws',
    rescueStatus: 'In Shelter',
    adoptionStatus: 'Available',
    healthStatus: 'Healthy',
    vaccinationStatus: 'Vaccinated',
    heartRate: 'Normal',
    location: 'Quezon City Rescue Center',
    dateRescued: '2026-06-01',
    dateAdded: '2026-06-03',
    lastUpdated: '2026-07-14',
    bio: 'Playful and curious kitty who loves window perches and feather toys.',
    photo: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?auto=format&fit=crop&w=600&q=80',
    ...NO_3D,
  },
  {
    id: 'A003',
    name: 'Bruno',
    species: 'Dog',
    breed: 'Aspin (Filipino Indigenous Dog)',
    sex: 'Male',
    age: '3 years',
    size: 'Medium',
    colorMarkings: 'Brown with black muzzle',
    rescueStatus: 'In Shelter',
    adoptionStatus: 'Available',
    healthStatus: 'Healthy',
    vaccinationStatus: 'Vaccinated',
    heartRate: 'Normal',
    location: 'Cebu Animal Shelter',
    dateRescued: '2026-04-20',
    dateAdded: '2026-04-22',
    lastUpdated: '2026-07-13',
    bio: 'Loyal and calm gentleman who already knows basic commands.',
    photo: 'https://images.unsplash.com/photo-1596492784531-6e6eb5ea9993?auto=format&fit=crop&w=600&q=80',
    ...NO_3D,
  },
  {
    id: 'A004',
    name: 'Bella',
    species: 'Dog',
    breed: 'Shih Tzu Mix',
    sex: 'Female',
    age: '6 years',
    size: 'Small',
    colorMarkings: 'White and brown',
    rescueStatus: 'In Shelter',
    adoptionStatus: 'Available',
    healthStatus: 'Recovering',
    vaccinationStatus: 'Vaccinated',
    heartRate: 'Normal',
    location: 'Davao Rescue Hub',
    dateRescued: '2026-06-15',
    dateAdded: '2026-06-17',
    lastUpdated: '2026-07-12',
    bio: 'Gentle senior who still has plenty of love to give. Good with children.',
    photo: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&w=600&q=80',
    ...NO_3D,
  },
  {
    id: 'A005',
    name: 'Oreo',
    species: 'Cat',
    breed: 'Domestic Shorthair',
    sex: 'Female',
    age: '4 months',
    size: 'Small',
    colorMarkings: 'Black and white tuxedo',
    rescueStatus: 'In Shelter',
    adoptionStatus: 'Available',
    healthStatus: 'Healthy',
    vaccinationStatus: 'Not Fully Vaccinated',
    heartRate: 'Normal',
    location: 'Makati City Animal Care',
    dateRescued: '2026-07-01',
    dateAdded: '2026-07-02',
    lastUpdated: '2026-07-14',
    bio: 'Tiny kitten with a big personality. Loves to play and cuddle.',
    photo: 'https://images.unsplash.com/photo-1513360371669-4adf3dd7dff8?auto=format&fit=crop&w=600&q=80',
    ...NO_3D,
  },
];
