import type { RescueCase, WorkflowAction } from '@/types';

export const INITIAL_DATA: RescueCase[] = [
  {
    id: 'REC-9011',
    animalType: 'Stray Cat',
    condition: 'Severe leg fracture near highway crossover',
    location: '7th Avenue Metropark, Near Shell Station',
    reporter: 'Jane Doe',
    priority: 'Critical',
    stage: 'New Reports',
    reportedDate: '2026-07-11 08:30 AM',
    imageUrl: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?q=80&w=500',
    coords: { lat: 40.7588, lon: -73.9851 },
    status: 'Pending Review',
    species: 'Feline',
    breed: 'Domestic Shorthair',
    estimatedAge: '1-2 Years',
    sex: 'Female',
    colorMarkings: 'Calico pattern, white mittens',
    size: 'Small',
    injuries: 'Open compounding fracture on rear right limb',
    temperament: 'Fearful, hissing but non-aggressive',
    collarTag: 'No',
    animalsInvolved: 1,
    lastSeen: '2026-07-11 08:15 AM',
    currentSituation: 'Hiding beneath temporary construction road barriers',
    barangay: 'San Antonio',
    landmarks: 'Opposite Metrobank Highway Depot',
    contactNumber: '+63 917 123 4567',
    email: 'jane.doe@example.com',
    reporterType: 'Citizen',
    anonymous: 'No',
    assignedRescuer: 'Officer Mark Mendoza',
    rescueTeam: 'Alpha Team Alpha',
    assignedDate: '2026-07-11 08:45 AM',
    eta: '25 Minutes',
    dispatchTime: '2026-07-11 08:50 AM',
    outcome: 'Pending Active Target Extrication',
    animalName: 'Unknown / Unassigned',
    incidentDescription: 'The dispatch case asset target manifests an active emergency state matching reported profile. Needs immediate triage context application.',
    additionalNotes: 'N/A - No auxiliary notes append records.',
    operationalStatus: 'In Progress',
    verificationStatus: 'Verified True Report',
    completionTime: '--:--',
    internalNotes: 'Deploying transport cage unit asset variants based on species matching profiles.',
    evidenceFileName: 'REC-9011_intake_primary.png',
    timelineSteps: [
      { title: 'Report Submitted', timestamp: '2026-07-11 08:30 AM', active: true },
      { title: 'Report Verified', timestamp: '2026-07-11 08:45 AM', active: true },
      { title: 'Rescuer Assigned & Dispatched', timestamp: 'Pending Progress Node', active: false }
    ]
  },
  {
    id: 'REC-9012',
    animalType: 'Abandoned Dog',
    condition: 'Extremely malnourished, tied outside warehouse infrastructure',
    location: 'Oakridge Subd. Plot 4B',
    reporter: 'Alex Smith',
    priority: 'High',
    stage: 'New Reports',
    reportedDate: '2026-07-11 06:12 AM',
    imageUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?q=80&w=500',
    coords: { lat: 34.0522, lon: -118.2437 },
    status: 'Pending Dispatch Logistics',
    species: 'Canine',
    breed: 'Askal / Mixed Breed',
    estimatedAge: '8-10 Months',
    sex: 'Male',
    colorMarkings: 'Light brown, white patches on chest',
    size: 'Medium',
    injuries: 'No visible deep wounds, clear physical skin dehydration',
    temperament: 'Friendly, tail-wagging but weak',
    collarTag: 'Yes (No engraving details available)',
    animalsInvolved: 1,
    lastSeen: '2026-07-11 06:00 AM',
    currentSituation: 'Leashed to a rusted iron storage pipe container',
    barangay: 'Dadiangas North',
    landmarks: 'Behind Old Port Cold Storage Facility',
    contactNumber: '+63 918 765 4321',
    email: 'alex.smith@example.com',
    reporterType: 'Volunteer',
    anonymous: 'No',
    assignedRescuer: 'Sarah Jenkins',
    rescueTeam: 'Delta Unit K9',
    assignedDate: '2026-07-11 07:00 AM',
    eta: '10 Minutes',
    dispatchTime: '2026-07-11 07:05 AM',
    outcome: 'Awaiting On-Site Arrival Assessment',
    animalName: 'Unknown / Unassigned',
    incidentDescription: 'Reporter flagged prolonged tethering with no visible food or water source nearby, urgent welfare concern.',
    additionalNotes: 'Reporter can meet field team on arrival for gate access.',
    operationalStatus: 'In Progress',
    verificationStatus: 'Verified True Report',
    completionTime: '--:--',
    internalNotes: 'Coordinating with warehouse site security for access clearance.',
    evidenceFileName: 'REC-9012_intake_primary.png',
    timelineSteps: [
      { title: 'Report Submitted', timestamp: '2026-07-11 06:12 AM', active: true },
      { title: 'Report Verified', timestamp: '2026-07-11 07:00 AM', active: true },
      { title: 'Rescuer Assigned & Dispatched', timestamp: '2026-07-11 07:05 AM', active: false }
    ]
  },
  {
    id: 'REC-8987',
    animalType: 'Injured Bird',
    condition: 'Wing damage after suspected window strike',
    location: 'Riverbend Commercial Plaza, Block C',
    reporter: 'Miguel Torres',
    priority: 'Medium',
    stage: 'Verified Reports',
    reportedDate: '2026-07-10 03:40 PM',
    imageUrl: 'https://images.unsplash.com/photo-1444464666168-49d633b86797?q=80&w=500',
    coords: { lat: 14.5995, lon: 120.9842 },
    status: 'Verified, Awaiting Assignment',
    species: 'Avian',
    breed: 'Eurasian Tree Sparrow',
    estimatedAge: 'Adult',
    sex: 'Unknown',
    colorMarkings: 'Brown crown, black cheek patch',
    size: 'Extra Small',
    injuries: 'Suspected fractured left wing, unable to fly',
    temperament: 'Docile, low energy response',
    collarTag: 'No',
    animalsInvolved: 1,
    lastSeen: '2026-07-10 03:35 PM',
    currentSituation: 'Sheltered inside a ventilated box by reporter pending pickup',
    barangay: 'Poblacion',
    landmarks: 'Ground floor entrance near Plaza Fountain',
    contactNumber: '+63 920 456 7890',
    email: 'miguel.torres@example.com',
    reporterType: 'Citizen',
    anonymous: 'No',
    assignedRescuer: 'Pending Assignment',
    rescueTeam: 'Pending Assignment',
    assignedDate: 'Not Yet Assigned',
    eta: 'Not Yet Calculated',
    dispatchTime: 'Not Yet Dispatched',
    outcome: 'Awaiting Team Assignment',
    animalName: 'Unknown / Unassigned',
    incidentDescription: 'Verification team confirmed injury consistent with a glass collision, bird is stable but grounded.',
    additionalNotes: 'Reporter is keeping the bird warm and dark per phone guidance already provided.',
    operationalStatus: 'Verified',
    verificationStatus: 'Verified True Report',
    completionTime: '--:--',
    internalNotes: 'Low mobility case, standard courier pickup sufficient, no specialist unit required.',
    evidenceFileName: 'REC-8987_intake_primary.png',
    timelineSteps: [
      { title: 'Report Submitted', timestamp: '2026-07-10 03:40 PM', active: true },
      { title: 'Report Verified', timestamp: '2026-07-10 04:10 PM', active: true },
      { title: 'Rescuer Assigned & Dispatched', timestamp: 'Pending Progress Node', active: false }
    ]
  },
  {
    id: 'REC-8990',
    animalType: 'Stray Puppy Litter',
    condition: 'Three puppies found near flooded drainage canal',
    location: 'Lower Cabuyao Creek Path',
    reporter: 'Anonymous',
    priority: 'High',
    stage: 'Verified Reports',
    reportedDate: '2026-07-10 05:55 AM',
    imageUrl: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?q=80&w=500',
    coords: { lat: 14.2726, lon: 121.1237 },
    status: 'Verified, Awaiting Assignment',
    species: 'Canine',
    breed: 'Mixed Breed Litter',
    estimatedAge: '4-6 Weeks',
    sex: 'Mixed',
    colorMarkings: 'Varied, brindle and black/white',
    size: 'Small',
    injuries: 'Mild hypothermia symptoms, no open wounds observed',
    temperament: 'Whimpering, huddled together for warmth',
    collarTag: 'No',
    animalsInvolved: 3,
    lastSeen: '2026-07-10 05:45 AM',
    currentSituation: 'Trapped on a narrow concrete ledge above rising canal water',
    barangay: 'Lower Bicutan',
    landmarks: 'Beneath the Cabuyao Creek Footbridge',
    contactNumber: 'Withheld by Reporter',
    email: 'Withheld by Reporter',
    reporterType: 'Citizen',
    anonymous: 'Yes',
    assignedRescuer: 'Pending Assignment',
    rescueTeam: 'Pending Assignment',
    assignedDate: 'Not Yet Assigned',
    eta: 'Not Yet Calculated',
    dispatchTime: 'Not Yet Dispatched',
    outcome: 'Awaiting Team Assignment',
    animalName: 'Unknown / Unassigned',
    incidentDescription: 'Field verification photos confirm three puppies stranded above canal water level, no mother observed at site.',
    additionalNotes: 'Water levels expected to keep rising through the afternoon per local weather advisory.',
    operationalStatus: 'Verified',
    verificationStatus: 'Verified True Report',
    completionTime: '--:--',
    internalNotes: 'Flag as time sensitive, prioritize water rescue equipped team for next dispatch cycle.',
    evidenceFileName: 'REC-8990_intake_primary.png',
    timelineSteps: [
      { title: 'Report Submitted', timestamp: '2026-07-10 05:55 AM', active: true },
      { title: 'Report Verified', timestamp: '2026-07-10 06:20 AM', active: true },
      { title: 'Rescuer Assigned & Dispatched', timestamp: 'Pending Progress Node', active: false }
    ]
  },
  {
    id: 'REC-8944',
    animalType: 'Injured Rabbit',
    condition: 'Predator attack wound along hind flank',
    location: 'Greenview Community Garden Lot 2',
    reporter: 'Priya Ramirez',
    priority: 'Medium',
    stage: 'Rescue Operations',
    reportedDate: '2026-07-09 01:10 PM',
    imageUrl: 'https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?q=80&w=500',
    coords: { lat: 14.5547, lon: 121.0244 },
    status: 'Active Field Operation',
    species: 'Lagomorph',
    breed: 'Domestic Rabbit, Escaped Pet',
    estimatedAge: '1 Year',
    sex: 'Female',
    colorMarkings: 'White with grey ear tips',
    size: 'Small',
    injuries: 'Laceration along hind flank, moderate bleeding controlled on site',
    temperament: 'Stressed, thumping but allows handling',
    collarTag: 'No',
    animalsInvolved: 1,
    lastSeen: '2026-07-09 01:00 PM',
    currentSituation: 'Contained in a carrier by rescue team, en route to partner clinic',
    barangay: 'Greenview',
    landmarks: 'Behind Community Garden Toolshed',
    contactNumber: '+63 927 334 8821',
    email: 'priya.ramirez@example.com',
    reporterType: 'Volunteer',
    anonymous: 'No',
    assignedRescuer: 'Officer Dana Reyes',
    rescueTeam: 'Bravo Field Unit',
    assignedDate: '2026-07-09 01:20 PM',
    eta: 'Arrived On Site',
    dispatchTime: '2026-07-09 01:25 PM',
    outcome: 'Secured, Transporting to Partner Veterinary Clinic',
    animalName: 'Unknown / Unassigned',
    incidentDescription: 'Field team confirmed a predator-related injury pattern, animal was successfully contained without further escape risk.',
    additionalNotes: 'Reporter has requested updates on recovery progress once intake is completed.',
    operationalStatus: 'In Progress',
    verificationStatus: 'Verified True Report',
    completionTime: '--:--',
    internalNotes: 'Clinic notified of estimated arrival window, wound care kit already prepped.',
    evidenceFileName: 'REC-8944_intake_primary.png',
    timelineSteps: [
      { title: 'Report Submitted', timestamp: '2026-07-09 01:10 PM', active: true },
      { title: 'Report Verified', timestamp: '2026-07-09 01:15 PM', active: true },
      { title: 'Rescuer Assigned & Dispatched', timestamp: '2026-07-09 01:25 PM', active: true }
    ]
  },
  {
    id: 'REC-8901',
    animalType: 'Stray Cat Colony',
    condition: 'Suspected mange outbreak among colony members',
    location: 'Fisherman\u2019s Wharf Access Road',
    reporter: 'Ben Alcaraz',
    priority: 'Medium',
    stage: 'Rescue Operations',
    reportedDate: '2026-07-08 09:20 AM',
    imageUrl: 'https://images.unsplash.com/photo-1533738363-b7f9aef128ce?q=80&w=500',
    coords: { lat: 14.5836, lon: 120.9720 },
    status: 'Active Field Operation',
    species: 'Feline',
    breed: 'Mixed Colony',
    estimatedAge: 'Varied, 6 Months - 4 Years',
    sex: 'Mixed',
    colorMarkings: 'Varied coat patterns across colony',
    size: 'Small to Medium',
    injuries: 'Patchy fur loss and skin irritation consistent with mange',
    temperament: 'Wary, feral behavior observed in most members',
    collarTag: 'No',
    animalsInvolved: 6,
    lastSeen: '2026-07-08 09:00 AM',
    currentSituation: 'Colony being trapped in stages using humane cage traps',
    barangay: 'Wharf District',
    landmarks: 'Adjacent to the Old Fish Market Loading Dock',
    contactNumber: '+63 933 220 1156',
    email: 'ben.alcaraz@example.com',
    reporterType: 'Community Caretaker',
    anonymous: 'No',
    assignedRescuer: 'Officer Mark Mendoza',
    rescueTeam: 'Alpha Team Alpha',
    assignedDate: '2026-07-08 09:40 AM',
    eta: 'Arrived On Site',
    dispatchTime: '2026-07-08 09:45 AM',
    outcome: 'Trap-Treat-Release Protocol In Progress',
    animalName: 'Unknown / Unassigned',
    incidentDescription: 'Longstanding caretaker flagged a worsening skin condition spreading through the colony over the past two weeks.',
    additionalNotes: 'Caretaker has been feeding the colony daily and can assist with trap placement timing.',
    operationalStatus: 'In Progress',
    verificationStatus: 'Verified True Report',
    completionTime: '--:--',
    internalNotes: 'Two of six colony members trapped so far, treatment schedule staggered across three days.',
    evidenceFileName: 'REC-8901_intake_primary.png',
    timelineSteps: [
      { title: 'Report Submitted', timestamp: '2026-07-08 09:20 AM', active: true },
      { title: 'Report Verified', timestamp: '2026-07-08 09:30 AM', active: true },
      { title: 'Rescuer Assigned & Dispatched', timestamp: '2026-07-08 09:45 AM', active: true }
    ]
  },
  {
    id: 'REC-9033',
    animalType: 'Injured Turtle',
    condition: 'Cracked shell after being struck on roadside',
    location: 'Marshview Access Trail, Km 3',
    reporter: 'Louie Fernandez',
    priority: 'Medium',
    stage: 'New Reports',
    reportedDate: '2026-07-11 09:05 AM',
    imageUrl: 'https://images.unsplash.com/photo-1437622368342-7a3d89d24870?q=80&w=500',
    coords: { lat: 14.4791, lon: 121.0198 },
    status: 'Pending Review',
    species: 'Reptile',
    breed: 'Asian Box Turtle',
    estimatedAge: 'Adult',
    sex: 'Unknown',
    colorMarkings: 'Dark brown shell, yellow head striping',
    size: 'Small',
    injuries: 'Hairline shell fracture along the carapace edge',
    temperament: 'Withdrawn into shell, minimal movement',
    collarTag: 'No',
    animalsInvolved: 1,
    lastSeen: '2026-07-11 09:00 AM',
    currentSituation: 'Placed in a shaded container by reporter beside the trail',
    barangay: 'Marshview',
    landmarks: 'Trailhead marker post 3',
    contactNumber: '+63 915 220 7743',
    email: 'louie.fernandez@example.com',
    reporterType: 'Citizen',
    anonymous: 'No',
    assignedRescuer: 'Pending Assignment',
    rescueTeam: 'Pending Assignment',
    assignedDate: 'Not Yet Assigned',
    eta: 'Not Yet Calculated',
    dispatchTime: 'Not Yet Dispatched',
    outcome: 'Pending Active Target Extrication',
    animalName: 'Unknown / Unassigned',
    incidentDescription: 'Reporter noted vehicle tire tracks near the site, shell integrity appears compromised but the turtle remains responsive.',
    additionalNotes: 'Reporter can remain on standby for the next hour.',
    operationalStatus: 'Pending',
    verificationStatus: 'Pending Verification',
    completionTime: '--:--',
    internalNotes: 'Route through wildlife rescue partner for shell repair once collected.',
    evidenceFileName: 'REC-9033_intake_primary.png',
    timelineSteps: [
      { title: 'Report Submitted', timestamp: '2026-07-11 09:05 AM', active: true },
      { title: 'Report Verified', timestamp: 'Pending Progress Node', active: false },
      { title: 'Rescuer Assigned & Dispatched', timestamp: 'Pending Progress Node', active: false }
    ]
  },
  {
    id: 'REC-9041',
    animalType: 'Kitten',
    condition: 'Trapped inside a roadside storm drain',
    location: 'Corner of Magsaysay St. and 5th St.',
    reporter: 'Cathy Villanueva',
    priority: 'High',
    stage: 'New Reports',
    reportedDate: '2026-07-11 10:48 AM',
    imageUrl: 'https://images.unsplash.com/photo-1495360010541-f48722b34f7d?q=80&w=500',
    coords: { lat: 14.6091, lon: 121.0223 },
    status: 'Pending Review',
    species: 'Feline',
    breed: 'Domestic Shorthair',
    estimatedAge: '3-4 Months',
    sex: 'Unknown',
    colorMarkings: 'Solid grey coat',
    size: 'Extra Small',
    injuries: 'No visible injuries, distressed vocalizing',
    temperament: 'Frightened, crying continuously',
    collarTag: 'No',
    animalsInvolved: 1,
    lastSeen: '2026-07-11 10:40 AM',
    currentSituation: 'Audible below the drain grate, unable to climb out',
    barangay: 'San Isidro',
    landmarks: 'Beside the Magsaysay Street covered walkway',
    contactNumber: '+63 921 884 3390',
    email: 'cathy.villanueva@example.com',
    reporterType: 'Citizen',
    anonymous: 'No',
    assignedRescuer: 'Pending Assignment',
    rescueTeam: 'Pending Assignment',
    assignedDate: 'Not Yet Assigned',
    eta: 'Not Yet Calculated',
    dispatchTime: 'Not Yet Dispatched',
    outcome: 'Pending Active Target Extrication',
    animalName: 'Unknown / Unassigned',
    incidentDescription: 'Reporter has been keeping watch at the drain grate to prevent the kitten from being flushed further in during light rain.',
    additionalNotes: 'Access will likely require lifting the drain grate on site.',
    operationalStatus: 'Pending',
    verificationStatus: 'Pending Verification',
    completionTime: '--:--',
    internalNotes: 'Bring grate lifting tool and a soft carrier for extraction.',
    evidenceFileName: 'REC-9041_intake_primary.png',
    timelineSteps: [
      { title: 'Report Submitted', timestamp: '2026-07-11 10:48 AM', active: true },
      { title: 'Report Verified', timestamp: 'Pending Progress Node', active: false },
      { title: 'Rescuer Assigned & Dispatched', timestamp: 'Pending Progress Node', active: false }
    ]
  },
  {
    id: 'REC-8999',
    animalType: 'Stray Goat',
    condition: 'Wandering onto an active highway shoulder',
    location: 'North Diversion Highway, Km 18',
    reporter: 'Rico Bautista',
    priority: 'Medium',
    stage: 'Verified Reports',
    reportedDate: '2026-07-10 11:20 AM',
    imageUrl: 'https://images.unsplash.com/photo-1524024973431-2ad916746881?q=80&w=500',
    coords: { lat: 14.8171, lon: 120.9302 },
    status: 'Verified, Awaiting Assignment',
    species: 'Caprine',
    breed: 'Mixed Breed Goat',
    estimatedAge: '2 Years',
    sex: 'Male',
    colorMarkings: 'White with brown facial patch',
    size: 'Medium',
    injuries: 'No visible injuries observed',
    temperament: 'Skittish around traffic noise',
    collarTag: 'Yes, faded rope tether remnant',
    animalsInvolved: 1,
    lastSeen: '2026-07-10 11:15 AM',
    currentSituation: 'Grazing along the highway shoulder guardrail',
    barangay: 'Sto. Rosario',
    landmarks: 'Near the Km 18 overpass',
    contactNumber: '+63 928 552 6610',
    email: 'rico.bautista@example.com',
    reporterType: 'Motorist',
    anonymous: 'No',
    assignedRescuer: 'Pending Assignment',
    rescueTeam: 'Pending Assignment',
    assignedDate: 'Not Yet Assigned',
    eta: 'Not Yet Calculated',
    dispatchTime: 'Not Yet Dispatched',
    outcome: 'Awaiting Team Assignment',
    animalName: 'Unknown / Unassigned',
    incidentDescription: 'Verification team confirmed a loose tether trailing behind the goat, likely strayed from a nearby smallholding.',
    additionalNotes: 'Highway patrol notified for traffic safety support during capture.',
    operationalStatus: 'Verified',
    verificationStatus: 'Verified True Report',
    completionTime: '--:--',
    internalNotes: 'Coordinate lane closure window with highway patrol before dispatch.',
    evidenceFileName: 'REC-8999_intake_primary.png',
    timelineSteps: [
      { title: 'Report Submitted', timestamp: '2026-07-10 11:20 AM', active: true },
      { title: 'Report Verified', timestamp: '2026-07-10 11:50 AM', active: true },
      { title: 'Rescuer Assigned & Dispatched', timestamp: 'Pending Progress Node', active: false }
    ]
  },
  {
    id: 'REC-9002',
    animalType: 'Injured Owl',
    condition: 'Grounded with a suspected leg injury',
    location: 'Hillcrest Orchard Access Road',
    reporter: 'Nadia Cruz',
    priority: 'Medium',
    stage: 'Verified Reports',
    reportedDate: '2026-07-10 07:44 PM',
    imageUrl: 'https://images.unsplash.com/photo-1543549790-8b03ffdc90ab?q=80&w=500',
    coords: { lat: 14.3487, lon: 121.0912 },
    status: 'Verified, Awaiting Assignment',
    species: 'Avian',
    breed: 'Philippine Scops Owl',
    estimatedAge: 'Adult',
    sex: 'Unknown',
    colorMarkings: 'Mottled brown and grey plumage',
    size: 'Small',
    injuries: 'Suspected fractured leg, unable to grip perches',
    temperament: 'Alert, defensive when approached',
    collarTag: 'No',
    animalsInvolved: 1,
    lastSeen: '2026-07-10 07:30 PM',
    currentSituation: 'Sheltered under a ventilated crate near the orchard fence line',
    barangay: 'Hillcrest',
    landmarks: 'Beside the Orchard Road Storage Shed',
    contactNumber: '+63 926 118 4402',
    email: 'nadia.cruz@example.com',
    reporterType: 'Citizen',
    anonymous: 'No',
    assignedRescuer: 'Pending Assignment',
    rescueTeam: 'Pending Assignment',
    assignedDate: 'Not Yet Assigned',
    eta: 'Not Yet Calculated',
    dispatchTime: 'Not Yet Dispatched',
    outcome: 'Awaiting Team Assignment',
    animalName: 'Unknown / Unassigned',
    incidentDescription: 'Field verification confirmed a nocturnal raptor grounded with limited mobility, likely from a night collision.',
    additionalNotes: 'Handle with raptor-safe gloves and minimal light exposure during transport.',
    operationalStatus: 'Verified',
    verificationStatus: 'Verified True Report',
    completionTime: '--:--',
    internalNotes: 'Flag for wildlife rehabilitation partner, not standard shelter intake.',
    evidenceFileName: 'REC-9002_intake_primary.png',
    timelineSteps: [
      { title: 'Report Submitted', timestamp: '2026-07-10 07:44 PM', active: true },
      { title: 'Report Verified', timestamp: '2026-07-10 08:20 PM', active: true },
      { title: 'Rescuer Assigned & Dispatched', timestamp: 'Pending Progress Node', active: false }
    ]
  },
  {
    id: 'REC-8955',
    animalType: 'Dog',
    condition: 'Struck by a vehicle, currently in transport',
    location: 'Eastbound Service Road, near Kilometer Post 6',
    reporter: 'Grace Lim',
    priority: 'Critical',
    stage: 'Rescue Operations',
    reportedDate: '2026-07-09 04:05 PM',
    imageUrl: 'https://images.unsplash.com/photo-1517849845537-4d257902861a?q=80&w=500',
    coords: { lat: 14.6255, lon: 121.0475 },
    status: 'Active Field Operation',
    species: 'Canine',
    breed: 'Askal / Mixed Breed',
    estimatedAge: '3 Years',
    sex: 'Male',
    colorMarkings: 'Black with white chest blaze',
    size: 'Medium',
    injuries: 'Suspected hind limb fracture, stabilized with a field splint',
    temperament: 'Subdued, in visible pain but not aggressive',
    collarTag: 'No',
    animalsInvolved: 1,
    lastSeen: '2026-07-09 04:00 PM',
    currentSituation: 'Loaded onto the rescue vehicle, en route to emergency clinic',
    barangay: 'Eastgate',
    landmarks: 'Near the Kilometer Post 6 pedestrian crossing',
    contactNumber: '+63 917 774 2201',
    email: 'grace.lim@example.com',
    reporterType: 'Motorist',
    anonymous: 'No',
    assignedRescuer: 'Sarah Jenkins',
    rescueTeam: 'Delta Unit K9',
    assignedDate: '2026-07-09 04:12 PM',
    eta: 'Arrived On Site',
    dispatchTime: '2026-07-09 04:15 PM',
    outcome: 'Secured, Transporting to Emergency Veterinary Clinic',
    animalName: 'Unknown / Unassigned',
    incidentDescription: 'First responders applied a temporary splint at the scene before transport to limit further injury during transit.',
    additionalNotes: 'Reporter waited on site until the rescue vehicle arrived.',
    operationalStatus: 'In Progress',
    verificationStatus: 'Verified True Report',
    completionTime: '--:--',
    internalNotes: 'Clinic pre-notified, surgical team on standby pending imaging results.',
    evidenceFileName: 'REC-8955_intake_primary.png',
    timelineSteps: [
      { title: 'Report Submitted', timestamp: '2026-07-09 04:05 PM', active: true },
      { title: 'Report Verified', timestamp: '2026-07-09 04:08 PM', active: true },
      { title: 'Rescuer Assigned & Dispatched', timestamp: '2026-07-09 04:15 PM', active: true }
    ]
  },
  {
    id: 'REC-8920',
    animalType: 'Cat Family',
    condition: 'Mother and three kittens rescued from a collapsed shed',
    location: 'Old Millworks Compound, Building 2',
    reporter: 'Tomas Reyes',
    priority: 'High',
    stage: 'Rescue Operations',
    reportedDate: '2026-07-08 02:30 PM',
    imageUrl: 'https://images.unsplash.com/photo-1592194996308-7b43878e84a6?q=80&w=500',
    coords: { lat: 14.5391, lon: 121.0089 },
    status: 'Active Field Operation',
    species: 'Feline',
    breed: 'Mixed, Mother and Litter',
    estimatedAge: 'Mother 2 Years, Kittens 5 Weeks',
    sex: 'Mixed',
    colorMarkings: 'Mother tabby, kittens varied',
    size: 'Small',
    injuries: 'Minor dust inhalation, no structural injuries found',
    temperament: 'Mother protective, kittens huddled and quiet',
    collarTag: 'No',
    animalsInvolved: 4,
    lastSeen: '2026-07-08 02:20 PM',
    currentSituation: 'Family unit contained together in a single carrier during extraction',
    barangay: 'Old Millworks',
    landmarks: 'Behind the Building 2 loading bay',
    contactNumber: '+63 919 662 5588',
    email: 'tomas.reyes@example.com',
    reporterType: 'Site Security',
    anonymous: 'No',
    assignedRescuer: 'Officer Dana Reyes',
    rescueTeam: 'Bravo Field Unit',
    assignedDate: '2026-07-08 02:45 PM',
    eta: 'Arrived On Site',
    dispatchTime: '2026-07-08 02:50 PM',
    outcome: 'Family Unit Secured, Monitoring for Air Quality Exposure',
    animalName: 'Unknown / Unassigned',
    incidentDescription: 'Partial roof collapse at the compound exposed a nesting site, rescue team extracted the family without separation.',
    additionalNotes: 'Site security is coordinating structural clearance before team re-entry for a final sweep.',
    operationalStatus: 'In Progress',
    verificationStatus: 'Verified True Report',
    completionTime: '--:--',
    internalNotes: 'Keeping mother and kittens housed together through observation period.',
    evidenceFileName: 'REC-8920_intake_primary.png',
    timelineSteps: [
      { title: 'Report Submitted', timestamp: '2026-07-08 02:30 PM', active: true },
      { title: 'Report Verified', timestamp: '2026-07-08 02:38 PM', active: true },
      { title: 'Rescuer Assigned & Dispatched', timestamp: '2026-07-08 02:50 PM', active: true }
    ]
  }
];

export const WORKFLOW_ACTIONS: WorkflowAction[] = [
  { id: 'verify', label: 'Verify Report' },
  { id: 'assign', label: 'Assign Rescuer' },
  { id: 'priority', label: 'Update Priority' },
  { id: 'status', label: 'Update Rescue Status' },
  { id: 'map', label: 'View Map' },
  { id: 'contact', label: 'Contact Reporter' },
  { id: 'notes', label: 'Add Notes' },
  { id: 'close', label: 'Close Case' }
];
