export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  ADMIN_LOGIN: '/admin-login',
  ADMIN: '/admin',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_ANIMALS: '/admin/animals',
  ADMIN_ANIMALS_NEW: '/admin/animals/new',
  ADMIN_ADOPTIONS: '/admin/adoptions',
  ADMIN_RESCUES: '/admin/rescues',
  ADMIN_HEALTH: '/admin/health',
  ADMIN_HEATMAP: '/admin/heatmap',
  ADMIN_ANALYTICS: '/admin/analytics',
  ADMIN_NOTIFICATIONS: '/admin/notifications',
  ADMIN_MESSAGES: '/admin/messages',
  ADMIN_LEARNING: '/admin/learning',
  ADMIN_USER: '/admin/user',
  ADMIN_SETTINGS: '/admin/settings',
  ADMIN_LOGS: '/admin/logs',
  ADMIN_CLINICS: '/admin/clinics',
} as const;
