import type { AdoptionApplication } from './types';

export const INITIAL_DATA: AdoptionApplication[] = [
  {
    id: 'APP-1024',
    applicantName: 'Sarah Jenkins',
    applicantEmail: 'sarah.j@example.com',
    animalName: 'Milo',
    animalPhoto: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?q=80&w=100&auto=format&fit=crop',
    species: 'Dog',
    applicationDate: '2026-07-10',
    status: 'Pending',
    assignedStaff: 'Unassigned',
  },
  {
    id: 'APP-1023',
    applicantName: 'David Chen',
    applicantEmail: 'dchen@example.com',
    animalName: 'Luna',
    animalPhoto: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?q=80&w=100&auto=format&fit=crop',
    species: 'Cat',
    applicationDate: '2026-07-08',
    status: 'Under Review',
    assignedStaff: 'Elena Rostova',
  },
  {
    id: 'APP-1022',
    applicantName: 'Marcus Thompson',
    applicantEmail: 'm.thompson@example.com',
    animalName: 'Rocky',
    animalPhoto: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?q=80&w=100&auto=format&fit=crop',
    species: 'Dog',
    applicationDate: '2026-07-05',
    status: 'Approved',
    assignedStaff: 'Marcus Vance',
  },
  {
    id: 'APP-1021',
    applicantName: 'Emma Watson',
    applicantEmail: 'emma.w@example.com',
    animalName: 'Bella',
    animalPhoto: 'https://images.unsplash.com/photo-1533738363-b7f9aef128ce?q=80&w=100&auto=format&fit=crop',
    species: 'Cat',
    applicationDate: '2026-07-02',
    status: 'Adopted',
    assignedStaff: 'Elena Rostova',
  },
  {
    id: 'APP-1020',
    applicantName: 'James Wilson',
    applicantEmail: 'jwilson@example.com',
    animalName: 'Zeus',
    animalPhoto: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?q=80&w=100&auto=format&fit=crop',
    species: 'Dog',
    applicationDate: '2026-06-28',
    status: 'Rejected',
    assignedStaff: 'System Risk Engine',
  },
  {
    id: 'APP-1019',
    applicantName: 'Priya Anand',
    applicantEmail: 'priya.a@example.com',
    animalName: 'Cooper',
    animalPhoto: 'https://images.unsplash.com/photo-1552053831-71594a27632d?q=80&w=100&auto=format&fit=crop',
    species: 'Dog',
    applicationDate: '2026-06-25',
    status: 'Adopted',
    assignedStaff: 'Marcus Vance',
  },
  {
    id: 'APP-1018',
    applicantName: 'Laura Bennett',
    applicantEmail: 'l.bennett@example.com',
    animalName: 'Whiskers',
    animalPhoto: 'https://images.unsplash.com/photo-1495360010541-f48722b34f7d?q=80&w=100&auto=format&fit=crop',
    species: 'Cat',
    applicationDate: '2026-06-20',
    status: 'Adopted',
    assignedStaff: 'Elena Rostova',
  },
  {
    id: 'APP-1017',
    applicantName: 'Noah Garcia',
    applicantEmail: 'noah.g@example.com',
    animalName: 'Buddy',
    animalPhoto: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?q=80&w=100&auto=format&fit=crop',
    species: 'Dog',
    applicationDate: '2026-06-14',
    status: 'Adopted',
    assignedStaff: 'Marcus Vance',
  },
  {
    id: 'APP-1016',
    applicantName: 'Sophie Turner',
    applicantEmail: 's.turner@example.com',
    animalName: 'Coco',
    animalPhoto: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?q=80&w=100&auto=format&fit=crop',
    species: 'Cat',
    applicationDate: '2026-06-09',
    status: 'Adopted',
    assignedStaff: 'Elena Rostova',
  },
];